# Generated by Django 5.1.5 on 2026-02-12 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_alter_project_status_alter_project_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='academic_group_name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
