# Generated by Django 5.1.5 on 2026-03-10 06:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_project_auto_generated_stages_projectstage_task_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectstage',
            name='template_section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stages', to='projects.projecttemplatesection'),
        ),
    ]
