# Generated by Django 5.1.5 on 2026-04-06 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0009_projectstage_template_section'),
    ]

    operations = [
        migrations.AddField(
            model_name='projecttemplate',
            name='format_profile',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('planned', 'Запланирован'), ('in_progress', 'В работе'), ('review', 'На проверке'), ('done', 'Завершен'), ('cancelled', 'Отменен')], default='planned', max_length=20),
        ),
        migrations.AlterField(
            model_name='project',
            name='type',
            field=models.CharField(choices=[('contest', 'Конкурс'), ('olympiad', 'Олимпиада'), ('coursework', 'Курсовой проект'), ('diploma', 'Дипломный проект'), ('other', 'Другое')], default='other', max_length=20),
        ),
        migrations.AlterField(
            model_name='projectstage',
            name='status',
            field=models.CharField(choices=[('open', 'Открыт'), ('submitted', 'Сдан на проверку'), ('changes_requested', 'Нужны доработки'), ('approved', 'Принят')], default='open', max_length=20),
        ),
        migrations.AlterField(
            model_name='projectstagereview',
            name='decision',
            field=models.CharField(choices=[('needs_changes', 'Нужны доработки'), ('approved', 'Принято')], max_length=20),
        ),
        migrations.AlterField(
            model_name='projectstagesubmission',
            name='status',
            field=models.CharField(choices=[('draft', 'Черновик'), ('submitted', 'На проверке'), ('needs_changes', 'Нужны доработки'), ('approved', 'Принято')], default='draft', max_length=20),
        ),
        migrations.AlterField(
            model_name='projectsupervisorinvite',
            name='status',
            field=models.CharField(choices=[('pending', 'Ожидает ответа'), ('accepted', 'Принято'), ('declined', 'Отклонено')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='projecttemplate',
            name='project_type',
            field=models.CharField(choices=[('contest', 'Конкурс'), ('olympiad', 'Олимпиада'), ('coursework', 'Курсовой проект'), ('diploma', 'Дипломный проект'), ('other', 'Другое')], default='other', max_length=20),
        ),
        migrations.AlterField(
            model_name='team',
            name='kind',
            field=models.CharField(choices=[('academic', 'Академическая группа'), ('creative', 'Команда')], default='creative', max_length=20),
        ),
    ]
