# Generated by Django 5.1.7 on 2026-04-09 07:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0010_projecttemplate_format_profile_alter_project_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='projectcomment',
            name='stage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='projects.projectstage'),
        ),
        migrations.AlterField(
            model_name='projectcomment',
            name='is_approved',
            field=models.BooleanField(default=True),
        ),
    ]
