# Generated by Django 5.1.7 on 2026-04-09 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0011_project_is_archived_projectcomment_stage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectstagereview',
            name='score',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
