# Generated by Django 5.1.7 on 2026-05-16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0012_projectstagereview_score"),
    ]

    operations = [
        migrations.AddField(
            model_name="projecttemplate",
            name="builder_schema",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
