# Generated by Django 5.1.5 on 2026-03-10 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('project_assigned', 'Project assigned'), ('team_invited', 'Invited to team'), ('supervisor_invited', 'Supervisor invited'), ('supervisor_invite_accepted', 'Supervisor invite accepted'), ('supervisor_invite_declined', 'Supervisor invite declined'), ('stage_created', 'Stage created'), ('stage_submitted', 'Stage submitted'), ('stage_reviewed', 'Stage reviewed'), ('comment_pending', 'Comment pending moderation'), ('project_publish_request', 'Project publish request')], max_length=40),
        ),
    ]
