# Generated by Django 5.1.7 on 2026-04-22 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_alter_notification_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('project_assigned', 'Назначен проект'), ('team_invited', 'Приглашение в команду'), ('supervisor_invited', 'Приглашение руководителю'), ('supervisor_invite_accepted', 'Приглашение руководителю принято'), ('supervisor_invite_declined', 'Приглашение руководителю отклонено'), ('stage_created', 'Создан этап'), ('stage_submitted', 'Этап отправлен'), ('stage_reviewed', 'Этап проверен'), ('comment_pending', 'Комментарий ожидает модерации'), ('project_publish_request', 'Запрос на публикацию проекта')], max_length=40),
        ),
    ]
